/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in installed projects.
// It is checked in here so TypeScript can understand Next types from the start.
